name: mini-tt
version: 1.0.0

dependencies:
- array
- base
- mtl

library:
  source-dirs: src

executables:
  agdacore:
    main: Main.hs
    source-dirs: app-agdacore
    dependencies:
    - mini-tt
  parse:
    main: Main.hs
    source-dirs: app-parse
    dependencies:
    - mini-tt
